import type { Metadata } from "next";
import { Afacad } from 'next/font/google';
import "./globals.css";

const afacad = Afacad({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
  display: 'swap',
  variable: '--font-afacad',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={afacad.className}>
      <body>{children}</body>
    </html>
  );
}
